name: Check formatting

on: [push, pull_request, workflow_dispatch]

jobs:
  check_formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8
      - name: Install dependencies
        run: |
          pnpm install
      - name: Check formatting
        run: |
          pnpm run format:check
