name: Run all tests

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8
      - name: Install dependencies
        run: |
          cargo install tree-sitter-cli
          export PATH="$HOME/.cargo/bin:$PATH"
      - name: Generate parser
        run: |
          pnpm generate
      - name: Run tests
        run: |
          pnpm test
